### ISSUE TITLE
Crash: SessionDao_Impl.fetchSessionsWithFilters

### ISSUE THREAD

**Issue by chepsi** [droidconKE/droidconKeKotlin#129]
We are facing this crash on production with the below stacktrace.

```
Fatal Exception: android.database.sqlite.SQLiteException: near "1": syntax error (code 1 SQLITE_ERROR): , while compiling: 1
       at android.database.sqlite.SQLiteConnection.nativePrepareStatement(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1055)
       at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:662)
       at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590)
       at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:61)
       at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
       at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:46)
       at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1556)
       at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1524)
       at androidx.sqlite.db.framework.FrameworkSQLiteDatabase.query(FrameworkSQLiteDatabase.kt:156)
       at androidx.room.RoomDatabase.query(RoomDatabase.kt:481)
       at androidx.room.util.DBUtil.query(DBUtil.kt:75)
       at com.android254.data.dao.SessionDao_Impl.fetchSessionsWithFilters(SessionDao_Impl.java:709)
       at com.android254.data.repos.SessionsManager$fetchAndSaveSessions$2.invokeSuspend(SessionsManager.kt:50)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
       at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by daniel-waiguru** [comment]
@chepsi can I take this one?

**Comment by chepsi** [comment]
Hey @daniel-waiguru absolutely. I have assigned it to you. Please feel free to ask any questions here on the issue.

**Comment by chepsi** [comment]
Closing this. marking it as stale.
