### ISSUE TITLE
Crash on Home Speakers Card Click

### ISSUE THREAD

**Issue by chepsi** [droidconKE/droidconKeKotlin#191]
When one is on the home screen and clicks on the Speakers card, there is a crash with the following message;

```
 java.lang.IllegalArgumentException: Navigation destination that matches request NavDeepLinkRequest{ uri=android-app://androidx.navigation//speaker_details/{speakerId} } cannot be found in the navigation graph NavGraph(0x0) startDestination={Destination(0x9f0a1621) route=/home}
                                                                                                    	at androidx.navigation.NavController.navigate(NavController.kt:1664)
                                                                                                    	at androidx.navigation.NavController.navigate(NavController.kt:1984)
                                                                                                    	at androidx.navigation.NavController.navigate$default(NavController.kt:1979)
                                                                                                    	at com.android254.presentation.common.navigation.NavigationKt$Navigation$2$1$2.invoke(Navigation.kt:45)
                                                                                                    	at com.android254.presentation.common.navigation.NavigationKt$Navigation$2$1$2.invoke(Navigation.kt:42)
```

**Comment by paulodhiambo** [comment]
@chepsi I'll pick this

**Comment by chepsi** [comment]
@paulodhiambo absolutely. Let me know if you need any help.
