### ISSUE TITLE
[Bug Report] App crashes on launch

### ISSUE THREAD

**Issue by BKMbigo** [droidconKE/droidconKeKotlin#233]
**Describe the bug**
The application crashes whenever I launch it. 

###### If you encounter this issue on your device, Go to settings and clear app data

**Expected behavior**
The application opens

**Screenshots**

https://github.com/droidconKE/droidconKeKotlin/assets/102836149/689d7510-2c28-4235-9b9b-21e052aa963c

**Recoin Version: (from Settings -> About):**

**Smartphone (please complete the following information):**
 - Device: HMD Global Nokia G21
 - OS: Android 12

**Additional context**
Stacktrace:
```
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Migration didn't properly handle: sponsors(ke.droidcon.kotlin.datasource.local.model.SponsorEntity).
   Expected:
      TableInfo{name='sponsors', columns={name=Column{name='name', type='TEXT', affinity='2', notNull=true, primaryKeyPosition=1, defaultValue='undefined'}, link=Column{name='link', type='TEXT', affinity='2', notNull=true, primaryKeyPosition=0, defaultValue='undefined'}, tagline=Column{name='tagline', type='TEXT', affinity='2', notNull=true, primaryKeyPosition=0, defaultValue='undefined'}, logo=Column{name='logo', type='TEXT', affinity='2', notNull=true, primaryKeyPosition=0, defaultValue='undefined'}, createdAt=Column{name='createdAt', type='TEXT', affinity='2', notNull=true, primaryKeyPosition=0, defaultValue='undefined'}}, foreignKeys=[], indices=[]}
   Found:
      TableInfo{name='sponsors', columns={}, foreignKeys=[], indices=[]}
         at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:516)
         at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:475)
         at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:317)
         at androidx.work.impl.utils.SerialExecutorImpl$Task.run(SerialExecutorImpl.java:96)
         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
         at java.lang.Thread.run(Thread.java:1012)
   Caused by: java.lang.IllegalStateException: Migration didn't properly handle: sponsors(ke.droidcon.kotlin.datasource.local.model.SponsorEntity).
      Expected:
         TableInfo{name='sponsors', columns={name=Column{name='name', type='TEXT', affinity='2', notNull=true, primaryKeyPosition=1, defaultValue='undefined'}, link=Column{name='link', type='TEXT', affinity='2', notNull=true, primaryKeyPosition=0, defaultValue='undefined'}, tagline=Column{name='tagline', type='TEXT', affinity='2', notNull=true, primaryKeyPosition=0, defaultValue='undefined'}, logo=Column{name='logo', type='TEXT', affinity='2', notNull=true, primaryKeyPosition=0, defaultValue='undefined'}, createdAt=Column{name='createdAt', type='TEXT', affinity='2', notNull=true, primaryKeyPosition=0, defaultValue='undefined'}}, foreignKeys=[], indices=[]}
       Found:
          TableInfo{name='sponsors', columns={}, foreignKeys=[], indices=[]}
             at androidx.room.RoomOpenHelper.onUpgrade(RoomOpenHelper.kt:94)
             at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onUpgrade(FrameworkSQLiteOpenHelper.kt:253)
             at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:416)
             at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:316)
             ...
```

As the issue affects migration of the room database, I assume that the issue will only affect early birds :bird:  who had installed a previous version of the application.

If you encounter the issue on your device, you have to clear storage of the application. Simply uninstalling and re-installing does not solve the issue.

**Comment by yveskalume** [comment]
I think we have to create a migration

**Comment by Borwe** [comment]
Hmm, is it okay to just set it to drop old sql on migration?

**Comment by chepsi** [comment]
Marking this as stale
